-- Allow the existing correct-submission trigger to award XP/shells.
-- A nested profile update is generated by trusted database code, whereas a
-- direct PostgREST PATCH executes at trigger depth 1 and remains blocked.
CREATE OR REPLACE FUNCTION public.protect_profile_privileges()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  caller_role text;
BEGIN
  IF auth.role() = 'service_role' OR pg_trigger_depth() > 1 THEN
    RETURN NEW;
  END IF;

  SELECT p.role INTO caller_role FROM public.profiles p WHERE p.id = auth.uid();
  IF caller_role = 'super_admin' THEN RETURN NEW; END IF;

  IF caller_role = 'admin' AND auth.uid() <> OLD.id THEN
    IF OLD.role IN ('super_admin', 'admin') OR NEW.role IN ('super_admin', 'admin') THEN
      RAISE EXCEPTION 'Only a super admin can manage privileged accounts' USING ERRCODE = '42501';
    END IF;
    RETURN NEW;
  END IF;

  IF NEW.role IS DISTINCT FROM OLD.role
     OR NEW.email IS DISTINCT FROM OLD.email
     OR NEW.shells IS DISTINCT FROM OLD.shells
     OR NEW.xp_points IS DISTINCT FROM OLD.xp_points
     OR NEW.level IS DISTINCT FROM OLD.level
     OR NEW.total_active_seconds IS DISTINCT FROM OLD.total_active_seconds THEN
    RAISE EXCEPTION 'Privileged profile fields cannot be changed by this user' USING ERRCODE = '42501';
  END IF;
  RETURN NEW;
END;
$$;
